### ISSUE TITLE
Use the Nominatim API

### ISSUE THREAD

**Issue by klokan** [klokantech/nlsgaz#3]
Remove the Google Gazetteer API and use Nominatim - as in https://github.com/klokantech/javascript

**Comment by daliborjanak** [comment]
http://klokantech.github.io/nlsgaz/

**Comment by klokan** [comment]
The UK gazetter from NLS is not anymore used now? It should stay - just for the world search the Google should be replaced by Nominatim.

**Comment by klokan** [comment]
Sorry. I take it back.
