### ISSUE TITLE
Parishes of England and Wales

### ISSUE THREAD

**Issue by klokan** [klokantech/nlsgaz#5]
The database of parishes of England and Wales has been added recently by hacking the compiled gaz.js.

> Yes, the England and Wales counties and parishes are in the gaz.js now at https://github.com/NationalLibraryOfScotland/NLSExploreGeoreferencedMapsOL3 and http://geo.nls.uk/maps/dev/NLSExploreGeoreferencedMapsOL3/index.html.

We should include them in the clean source code - before compilation.

**Comment by daliborjanak** [comment]
@klokan, list of parishes is in https://github.com/klokantech/nlsgaz/blob/master/src/countyparishdata.js and it's now compiled together with sources.

You mean update it??

**Comment by klokan** [comment]
Yes.
