### ISSUE TITLE
Integration isssues

### ISSUE THREAD

**Issue by klokan** [klokantech/nlsgaz#6]
Reported problem:

> If you test your new gaz.js at http://klokantech.github.io/nlsgaz/gaz.js with the Github demo I provided at: https://github.com/NationalLibraryOfScotland/NLSExploreGeoreferencedMapsOL3 the gazetteer itself generates an error ‘TypeError: x is not a function’ in line 73 of gaz.js
> 
> You can see this too with the viewer at: http://geo.nls.uk/maps/dev/NLSExploreGeoreferencedMapsOL3/index.html which is using your new gaz.js
> 
> It also now generates the URL parameters nlsgaz=   &county= which we do not want and it did not do before.
> 
> I suspect this is due to the way you have compiled it with plover or Google closure tools, maybe? I see your version at http://klokantech.github.io/nlsgaz/ is working okay, but I would be very grateful if you help over how I can implement it here like the old gaz.js – without re-writing other parts of the application to fit with your new gaz.js.

**Comment by daliborjanak** [comment]
The problem started collision with other JS files. I wrapped gaz.js to function and I also added jquery externs. New build is in gh-pages branch:
https://github.com/klokantech/nlsgaz/blob/gh-pages/gaz.js

In html page:
- It's not necessary to linking google apis now
- Would be better to link search Text.js after Jquery - it's now prints error in console

I prepared gits with right itegration (see changes at lines 26, 125, 129:
https://gist.github.com/daliborjanak/4a769f11d68b40ac7f07

@klokan can you please report it to NLS, then close

**Comment by ChrisFleet** [comment]
Thanks for your quick work, Dalibor - this has fixed the problems mentioned above.

The main remaining problem I think is that National Grid Reference searches are searching Nominatim, I think, and not working. National Grid Reference searches are like NT1234   NS123456  TQ23 etc. and I can't get these to work either at http://klokantech.github.io/nlsgaz/

Chris

**Comment by daliborjanak** [comment]
@ChrisFleet 
I didn't know about this functionality, I had to remove it with old search. I fixed it yet. Also new build is on gh-pages. I hope it's ok now.

**Comment by ChrisFleet** [comment]
Many thanks, Dalibor - this works perfectly and I have this morning just updated all the NLS web-mapping viewers with your new code:
http://maps.nls.uk/geo/find/
http://maps.nls.uk/geo/explore/
etc.

Very grateful for your help and this project can be closed and signed off.

**Comment by klokan** [comment]
Thank you Dalibor! Well done work!

**Comment by ChrisFleet** [comment]
Dalibor / Petr,

This maybe a temporary problem after a few months when nlsgaz has worked fine, but today we have noticed the gazetteer at http://maps.nls.uk/geo/find and at http://klokantech.github.io/nlsgaz/ is broken - we are getting a MapQuest 403 Forbidden error:

NetworkError: 403 Forbidden - http://open.mapquestapi.com/nominatim/v1/search?q=

Please could you look into this?

Thanks,

Chris

**Comment by daliborjanak** [comment]
It looks that MapQuest changed API for searching. A created issue #7 with it. I will check it tomorrow.
