### ISSUE TITLE
MapQuest nominatim error

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/nlsgaz#7]
Dalibor / Petr,

This maybe a temporary problem after a few months when nlsgaz has worked fine, but today we have noticed the gazetteer at http://maps.nls.uk/geo/find and at http://klokantech.github.io/nlsgaz/ is broken - we are getting a MapQuest 403 Forbidden error:

NetworkError: 403 Forbidden - http://open.mapquestapi.com/nominatim/v1/search?q=

Please could you look into this?

Thanks,

Chris

**Comment by daliborjanak** [comment]
It looks that MapQuest changed API for searching. I will check it tomorrow.

**Comment by daliborjanak** [comment]
@ChrisFleet i fix it now temporary (new build at http://klokantech.github.io/nlsgaz). MapQuest changed api. MapQuest API needs now access key for it's services (it also have new pricing plan). We used temporary MZK service but we have to create our own. Peter will discus it with you.

**Comment by ChrisFleet** [comment]
Many thanks indeed, Dalibor – I’ve implemented this now on our live applications and it is all working fine. Petr explained all the background too.

Very grateful to you for doing this so quickly.

Chris

**Comment by ChrisFleet** [comment]
Hello Dalibor / Petr,

Just in case you don’t know, the gazetteer is giving a "NetworkError: 503 Service Unavailable - http://nominatim.klokantech.com/ at http://klokantech.github.io/nlsgaz/

Chris

**Comment by klokan** [comment]
Maintenance is happening on the server in MZK.
Should be fixed within about 30 minutes.

**Comment by ChrisFleet** [comment]
Hello Petr / Dalibor,

I'm sure you know, but just in case, I'm afraid we are getting 'NetworkError: 400 Bad Request - http://nominatim.klokantech.com/?q..' at http://klokantech.github.io/nlsgaz/ 

Chris

**Comment by klokan** [comment]
Reported to NLS.

On Tue, Oct 20, 2015 at 4:38 PM, ChrisFleet <notifications@github.com>
wrote:

> Hello Petr / Dalibor,
>
> I'm sure you know, but just in case, I'm afraid we are getting
> 'NetworkError: 400 Bad Request - http://nominatim.klokantech.com/?q..' at
> http://klokantech.github.io/nlsgaz/
>
> Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/klokantech/nlsgaz/issues/7#issuecomment-149587658>.
>



-- 
Petr Pridal, Ph.D.
CEO

Klokan Technologies GmbH
Hofnerstrasse 98, 6314 Unterageri, Switzerland
Tel: +41 (0)41 511 26 12
Email: info@klokantech.com
Web: http://www.klokantech.com/

**Comment by klokan** [comment]
Reported to MZK.

We really should schedule the development of our own code for gazetteer search...

Chris, shall I start a new project for this?
Would you be willing to cover about 16 hours of work on this (open-source) project to cover part of the development costs?

**Comment by klokan** [comment]
Fixed.

Still - reaction to questions above from Chris would be helpful...

**Comment by ChrisFleet** [comment]
Petr,

Many thanks indeed for fixing this so quickly.

Of course, I would be keen for a better solution, and keen to fund Klokan work – however, NLS does not have committed funds for paying an additional 16 hours before April 2016 – it would be only if the Subscription API were to generate income for us. So I feel nervous of just saying yes to this – we have so many things we want you to do, but limited money…

Chris
